package ui.Patient;

import Business.RequestFramework.*;
import Business.userAccount.Users;
import Business.RequestFramework.SensorRequestFramework;
import Business.RequestFramework.RequestFramework;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aayush
 */
public class ViewHelpRequestHistory extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Users users;
    /**
     * Creates new form ViewHelpRequestHistory
     */
    public ViewHelpRequestHistory(JPanel userProcessContainer, Users users) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.users = users;
        
       populateHelpSeekerRequestsHistoryTable();
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        int w = getWidth();
        int h = getHeight();
        
        Color c1 = new Color(210,240,114);
         Color c2 = new Color(210,240,114);
     
        GradientPaint gp = new GradientPaint(w/4, 0, c2, w/4, h, c1);
        setOpaque( false );
        g2d.setPaint(gp);
        g2d.fillRect(0, 0, w, h);
        setOpaque( true );
    }
    
    public void populateHelpSeekerRequestsHistoryTable()
    {
     DefaultTableModel dtm = (DefaultTableModel)workRequestHistoryTable.getModel();
        dtm.setRowCount(0);
         DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy"); 
     for(RequestFramework workRequestFramework : users.getRequestPipeline().getRequestList())
        {
         
           Object[] rowData = new Object[5];
           rowData[0] = workRequestFramework.getReqMessage();
           rowData[1] = dateFormat.format(workRequestFramework.getRequestDate());
           rowData[2] = workRequestFramework.getReceiverDetails() == null ? null : workRequestFramework.getReceiverDetails().getName() ;
           rowData[3] = workRequestFramework.getStatusOfRequest();
           if(workRequestFramework.getReqMessage().equalsIgnoreCase("Need GetHelp"))
           {
            HelpRequestFrameworkFramework nhwr = (HelpRequestFrameworkFramework) workRequestFramework;
            rowData[4] = nhwr.getRequestOutcome();   
           }
           else if(workRequestFramework.getReqMessage().equalsIgnoreCase("Need Sensor Device"))
           {
               SensorRequestFramework nsdwr = (SensorRequestFramework) workRequestFramework;
                 rowData[4] = nsdwr.getSponsorshipRequestOutcome();
           }
           else if(workRequestFramework.getReqMessage().equalsIgnoreCase("Vital Sign Data"))
           {
                DoctorDataSenderRequestFramework sdtdwr = (DoctorDataSenderRequestFramework) workRequestFramework;
                 rowData[4] = sdtdwr.getReqResult();
           }
           else
           {
                rowData[4] = "";
           }
           dtm.addRow(rowData);
        
        }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestHistoryTable = new javax.swing.JTable();
        manageEnt = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 255, 204));

        workRequestHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "GetHelp Recieved", "Requested Date", "Reciever ", "Status", "Request Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(workRequestHistoryTable);

        manageEnt.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        manageEnt.setText("View History of GetHelp Requests");

        backJButton.setBackground(new java.awt.Color(0, 153, 255));
        backJButton.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<< Back");
        backJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(backJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(manageEnt)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(manageEnt)
                .addGap(67, 67, 67)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(backJButton)
                .addGap(55, 55, 55))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel manageEnt;
    private javax.swing.JTable workRequestHistoryTable;
    // End of variables declaration//GEN-END:variables
}
