
package ui.SystemAdmin;

import Business.NetworkHelp;
import Business.Functions.GetHelp;
import Business.Functions.RegexValidation;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author prasanna
 */
public class CreateHelpJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private NetworkHelp system;


    /**
     * Creates new form CreateHelpJPanel
     */
    public CreateHelpJPanel(JPanel userProcessContainer, NetworkHelp system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        

        addInputVerifiers();
        populateComboBxHelpType();
    }
    
    
     @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        int w = getWidth();
        int h = getHeight();
        
        Color c1 = new Color(210,240,114);
         Color c2 = new Color(210,240,114);
         // Color c2 = color.white;
     
        GradientPaint gp = new GradientPaint(w/4, 0, c2, w/4, h, c1);
        setOpaque( false );
        g2d.setPaint(gp);
        g2d.fillRect(0, 0, w, h);
        setOpaque( true );
    }
    
    public void populateComboBxHelpType()
    {
      helpTypeComboBx.removeAllItems();
      helpTypeComboBx.addItem("Immediate");
      helpTypeComboBx.addItem("Need in a day");
      helpTypeComboBx.addItem("Not Immediate service");
      helpTypeComboBx.addItem("In a Week");
    }
    
     private void addInputVerifiers() {
        InputVerifier stringValidation = new RegexValidation();
        helpnameJTxtField.setInputVerifier(stringValidation);
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageEnt2 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        helpnameJTxtField = new javax.swing.JTextField();
        helpName = new javax.swing.JLabel();
        createHelpJButton = new javax.swing.JButton();
        helpType = new javax.swing.JLabel();
        manageEnt1 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        helpTypeComboBx = new javax.swing.JComboBox();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 0));

        manageEnt2.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        manageEnt2.setText("Health Hub");

        jLayeredPane1.setBackground(new java.awt.Color(193, 250, 144));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        helpName.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        helpName.setText("GetHelp Offered");

        createHelpJButton.setBackground(new java.awt.Color(0, 153, 255));
        createHelpJButton.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        createHelpJButton.setText("Create GetHelp");
        createHelpJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createHelpJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createHelpJButtonActionPerformed(evt);
            }
        });

        helpType.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        helpType.setText("GetHelp Type");

        manageEnt1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        manageEnt1.setText("Create GetHelp Offerred");

        cancelBtn.setBackground(new java.awt.Color(0, 153, 255));
        cancelBtn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        helpTypeComboBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        helpTypeComboBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpTypeComboBxActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(helpnameJTxtField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(helpName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(createHelpJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(helpType, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(manageEnt1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cancelBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(helpTypeComboBx, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(helpName)
                            .addComponent(helpType))
                        .addGap(29, 29, 29)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(helpTypeComboBx, 0, 215, Short.MAX_VALUE)
                            .addComponent(helpnameJTxtField)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(createHelpJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(manageEnt1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(manageEnt1)
                .addGap(38, 38, 38)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(helpName)
                    .addComponent(helpnameJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(helpType)
                    .addComponent(helpTypeComboBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createHelpJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        backJButton.setBackground(new java.awt.Color(0, 153, 255));
        backJButton.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185)
                        .addComponent(manageEnt2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageEnt2))
                .addGap(31, 31, 31)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createHelpJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createHelpJButtonActionPerformed
       
        if(helpnameJTxtField.getText().trim().isEmpty() || helpTypeComboBx.getSelectedIndex()<0)
       {
            JOptionPane.showMessageDialog(this, "Please enter data in all fields", "warning", JOptionPane.WARNING_MESSAGE);
            return;   
       }
        GetHelp needGetHelp = system.addHelp();
        needGetHelp.setHelp(helpnameJTxtField.getText());
        needGetHelp.setServiceType((String)helpTypeComboBx.getSelectedItem());
     
        JOptionPane.showMessageDialog(this, "GetHelp has been created successfully", "success", JOptionPane.PLAIN_MESSAGE);
           
        resetFields();
        
    }//GEN-LAST:event_createHelpJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
      resetFields();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void helpTypeComboBxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpTypeComboBxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpTypeComboBxActionPerformed

    public void resetFields()
    {
        helpnameJTxtField.setText("");
       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton createHelpJButton;
    private javax.swing.JLabel helpName;
    private javax.swing.JLabel helpType;
    private javax.swing.JComboBox helpTypeComboBx;
    private javax.swing.JTextField helpnameJTxtField;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel manageEnt1;
    private javax.swing.JLabel manageEnt2;
    // End of variables declaration//GEN-END:variables
}
